<table border="1" cellpadding="10" cellspacing="1" style="margin:1px" width="100%">
<tbody>
<tr>
<td align="center" bgcolor="#2f815f" valign="top" width="20%"><span style="font-size:16px;font-weight:bold;color:rgb(246,196,83)">TOOLS AVAILABLE</s</td>
 
<td align="center" bgcolor="#2f815f" valign="top" width="40%"><span style="font-size:16px;font-weight:bold;color:rgb(246,196,83)">RESOURCES</sd>

<td align="center" bgcolor="#2f815f" valign="top" width="40%"><span style="font-size:16px;font-weight:bold;color:rgb(246,196,83)">HOW TO USE THEM</span></td>
</tr>

<tr>
<td><b>Google email groups</b></td>
<td>Start by <a href="https://groups.google.com/my-groups?create-group=1" target="_blank">creating an email group for your team,</a>within Shopify's email group collection. For more info visit: <a href="https://vault.shopify.io/pages/5061-Google-Groups-at-Shopify" target="_blank">Vault - Google Groups.</a></td>
<td><a href="https://support.google.com/a/users/answer/9303222#2.1" target="_blank">Google Help Center - Create a group for your team</a></td>
</tr>

<tr>
<td><b>Slack</b></td>
<td><a href="https://slack.com/intl/en-ie/help/articles/201402297-Create-a-channel" target="_blank">Create a channel for your team, if you don't have one already.</a></td>
<td><ul><li><a href="https://vault.shopify.io/pages/394-Slack" target="_blank">Vault:Intro to Slack</a></li></ul><ul><li><a href="https://slack.com/intl/en-ie/help/articles/217626558-Keep-up-with-whats-important" target="_blank">Keep up with what's important</a></li></ul><ul><li><a href="https://slack.com/intl/en-ie/help/articles/360058495594-Focus-on-what-matters-to-you#create-custom-sections-1" target="_blank">Focus on what matters to you</a></li></ul><ul><li><a href="https://docs.google.com/spreadsheets/d/1R-2H05eVe6XJBU1YH3Rqv0uUv78MUk032Fpvib2MezA/edit#gid=919271968" target="_blank">Join ML channels mentioned here</a></li></ul></td></tr>

<tr>
<td><b>Access for Leads</b></td>
<td><ul>1. Guru Card Collections</ul><ul>2. Slack Channels</ul><ul>3. Leads Email list</ul><ul>4. Zendesk Role change</ul></td>
<td><ul>1. Reach out on <b style="color:blue;">#help-guru-tool</b> to request access to the Team Lead Guru Card collections.</ul><ul>2. Reach out to fellow leads or your SL to gain access to TL channels.</ul><ul>3. Once your role changes in workday, you will automatically be added to the TL email lists.</ul><ul>4. Reach out to <b style="color:blue;">#help-it</b> to request a role change for Zendesk.</ul></td>
</tr>

<tr>
<td><b>Zendesk</b></td>
<td>Team group</td>
<td>Once your Zendesk role has changed. Ask IT to create a group for your team, and add all your team members to it. This will help you be able to <a href="https://app.getguru.com/card/ec8go7jc/Zendesk-Squad-views" target="_blank">create teamwise Zendesk views</a> like Team PQ. </td>
</tr>

<tr>
<td><b>Calendar</b></td>
<td>Start building up your calendar and recurring meetings like: Jump, TTs, 1t1ts with your direct reports.</td>
<td>Check other Leads Calendar for ideas on how to best organise your time.
<a href="https://support.google.com/a/users/answer/9302892?hl=en" target="_blank">Google Help Center - What can you do with Calendar?</a> </td>
</tr>

<tr>
<td><b>Gmail</b></td>
<td><ul><li><a href="https://support.google.com/a/users/answer/9308990?hl=en" target="_blank">Create email templates</a></li></ul><ul><li><a href="https://vault.shopify.io/pages/3620-How-to-Manage-Gmail" target="_blank">How-to-Manage-Gmail</a></li></ul><ul><li><a href="https://degreed.com/pathway/79xjj1ekpk?path=managing-your-inbox" target="_blank">Managing Your Inbox - Degreed Pathway</a></li></ul></td>
<td>Organise your inbox by creating labels and templates which will allow you to easily separate your emails by importance of reading or actioning.</td>
</tr>

<tr>
<td><b>Google Meet</b></td>
<td><a href="https://support.google.com/a/users/answer/9300131?hl=en" target="_blank">Google Help Center - Google Meet cheat sheet</a></td>
<td>Find out more about the google meet features available. </td>
</tr>

<tr>
<td><b>Fellow</b></td>
<td><ul><li><a href="https://app.getguru.com/card/TEBx9Azc/Fellow-Templates-for-Squad-Leads" target="_blank">Guru Card - Fellow-Templates</a></li></ul><ul><li><a href="https://vault.shopify.io/pages/773-Fellow" target="_blank">Vault - Fellow intro</a></li></ul><ul><li><a href="https://help.fellow.app/" target="_blank">Fellow Support Help Center</a></li></ul></td>
<td>Creating templates for recurring meetings will help you work efficiently and reduce repetitive work.</td>
</tr>

<tr>
<td><b>Notes</b></td>
<td><a href="https://support.google.com/a/users/answer/9310171?hl=en" target="_blank">Google Help Center - Google Notes</a></td>
<td>Use Google Notes or any other Notes app/tool to keep notes.</td>
</tr>

<tr>
<td><b>Multilingual Teams  Worksheet</b></td>
<td><a href="https://docs.google.com/spreadsheets/d/1R-2H05eVe6XJBU1YH3Rqv0uUv78MUk032Fpvib2MezA/edit#gid=1208757859" target="_blank">Language Care Teams Worksheet</a></td>
<td>Review the <b>Legend</b> tab to find out what each tab is used for :)</td>
</tr>

<tr>
<td><b>Team Leads Rotation </b></td>
<td><a href="https://docs.google.com/spreadsheets/d/1R-2H05eVe6XJBU1YH3Rqv0uUv78MUk032Fpvib2MezA/edit#gid=659339144" target="_blank">TL Rotation schedule</a></td>
<td>Review when is your turn to work during weekends & setup a recurring reminder in your calendar to easily organise your weeks.</td>
</tr>

<tr>
<td><b>Workday</b></td>
<td><ul><li><a href="https://vault.shopify.io/pages/1783-Workday-for-Leads" target="_blank">Workday-for-Leads</a></li></ul><ul><li><a href="https://vault.shopify.io/pages/779-Approving-Time-Off-Expenses-and-Travel" target="_blank">Approving Expenses</a></li></ul><ul><li><a href="https://vault.shopify.io/pages/1389-Submitting-Time-Off-Requests" target="_blank">Vacation request for leads</a></li></ul></td>
<td>Learn more about what you can do in Workday.</td>
</tr>

<tr>
<td><b>Teleopti</b></td>
<td><ul><li><a href="https://app.getguru.com/card/T4kAKx8c/Team-Leads-Introduction-to-Teleopti" target="_blank">Team-Leads-Introduction-to-Teleopti</a></li></ul><ul><li><a href="https://app.getguru.com/card/5TjaRXaT/Workforce-Planning-Getting-in-touch-with-us" target="_blank">Workforce-Planning-Getting-in-touch-with-us</a></li></ul><ul><li><a href="https://app.getguru.com/card/iLkEzpKT/Team-Lead-Scheduling-Best-Practices-Intro" target="_blank">Team-Lead-Scheduling-Best-Practices-Intro</a></li></ul><ul><li><a href="https://app.getguru.com/card/9Tenp8xT/Workforce-Planning-Things-WFP-doesnt-need-to-be-contacted-for" target="_blank">Workforce Planning - Things WFP doesn't need to be contacted for</a></li></ul><ul><li><a href="https://app.getguru.com/card/pTqxRXeT/Team-Contacts-and-WFP" target="_blank">Team-Contacts-and-WFP</a></li></ul></td>
<td>Setup peer leads 1t1s and/or setup a meeting with WFP to gather more context on how Teleopti works.</td>
</tr>

<tr>
<td><b>MaestroQA</b></td>
<td><ul><li><a href="https://vault.shopify.io/pages/8490-Support-Quality-Assurance-resources-for-leads-mentors-and-agents" target="_blank">Support-Quality-Assurance-resources-for-leads</a></li></ul><ul><li><a href="https://app.getguru.com/card/iBEErnzT/Quality-Score-Getting-started-with-quality-at-Shopify-a-guide-for-leads-and-mentors" target="_blank">Getting started with quality at Shopify - a guide for leads and mentors</a></li></ul><ul><li><a href="https://app.getguru.com/boards/6TE5nL4T/Quality-Assurance" target="_blank">Guru Card collection - MaestroQA</a></li></ul></td>
<td>MaestroQA is the tool we use to grade tickets for our direct reports.</td>
</tr>

<tr>
<td><b>Bridge</b></td>
<td><ul><li><a href="https://vault.shopify.io/pages/2441-Bridge" target="_blank">Bridge Intro</a></li></ul><ul><li><a href="https://app.getguru.com/boards/9ixL4ori/Bridge" target="_blank">Guru Cards - Bridge Collection</a></li></ul><ul><li><a href="https://app.getguru.com/card/aiz55ppi/Bridge-for-leads-Intro" target="_blank">Bridge for leads - Intro</a></li></ul><ul><li><a href="https://data.shopify.com/reports/support-bridge-course-completion/runs/000b73e3582b" target="_blank">Bridge Course Completion Report</a></li></ul></td>
<td><ul><li>You will need author access in order to create and assign courses in Bridge across Shopify. Manager permissions in Bridge are automatically synced within 24 hours of your Workday being updated.</li></ul><ul><li>Leads have access to manager functions in Bridge, and can manage their team's course enrollments.</li></ul><ul><li>Use the report to keep track of your teams training completion.</li></ul></td>
</tr>

<tr>
<td><b>Degreed</b></td>
<td><a href="https://vault.shopify.io/pages/2059-Degreed" target="_blank">Degreed intro</a></td>
<td>Use degreed to find Pathways that would help you and your team develop.</td>
</tr>

<tr>
<td><b>Helpdesk</b></td>
<td><a href="https://app.getguru.com/card/Liaz76pi/IT-Team-Contact-info-supported-tools" target="_blank">IT-Team-Contact-info-supported-tools</a></td>
<td>Use Helpdesk to raise any IT related requests.</td>
</tr>

<tr>
<td><b>Airtable</b></td>
<td><ul>1. <a href="https://airtable.com/shr1EGUDPyHoWrju8/tblmjemt3Sre85gY8?blocks=hide" target="_blank">All hires start time</a></ul><ul>2. <a href="https://airtable.com/shrYvcT4zKQU9t6WK/tblmjemt3Sre85gY8?blocks=hide" target="_blank">ML hires start time</a></ul><ul>3. <a href="https://airtable.com/shrNSB5y02a8jGInF" target="_blank">Training Notes on new direct reports</a></ul></td>
<td><ul>1. <b style="color:blue;">Password: </b>87ovoidpigmenTs</ul><ul>2. <b style="color:blue;">Password: </b>Eleven2</ul><ul>3. <b style="color:blue;">Password: </b>hfgs75bd8</ul></td>
</tr>

<tr>
<td><b>GitHub</b></td>
<td><a href="https://vault.shopify.io/pages/605-GitHub" target="_blank">Getting Started with GitHub</a></td>
<td>Setting up a GitHub account allows you to participate in important discussions about how our products are changing on a day-to-day basis.</td>
</tr>

<tr>
<td><b>Projects Multilingual</b></td>
<td><a href="https://vault.shopify.io/teams/1904-Multilingual-Support-Team/work?subteams=yes&order=progress_asc&page=first_25&progress=Think_Explore_Build_Ongoing" target="_blank">Multilingual Support Projects </a></td>
<td>Directory of all ongoing ML projects</td>
</tr>

<tr>
<td><b>Impact Reviews</b></td>
<td><a href="https://vault.shopify.io/pages/7100-Impact-Review-Steps" target="_blank">Impact-Review-Steps</a></td>
<td>Additional information about the Impact Review.</td>
</tr>

<tr>
<td><b>Leads Resources</b></td>
<td><a href="https://vault.shopify.io/pages/222-Tools-for-Shopifolk" target="_blank">Vault - All available tools </a></td>
<td>Review all available tools, some could be useful in your day to day.</td>
</tr>

<tr>
<td><b>Localization</b></td>
<td><a href="https://vault.shopify.io/teams/1361-Localization/details" target="_blank">Vault - Localization/details</a></td>
<td>Find out more about the Localization team and what they do.</td>
</tr>

<tr>
<td><b>Zendesk Explore</b></td>
<td><a href="https://support.zendesk.com/hc/en-us/articles/360022178794-Getting-started-with-Explore-Walkthrough" target="_blank">Getting-started-with-Explore-Walkthrough</a></td>
<td>Zendesk Explore helps you create specific reports and track your teams performance.</td>
</tr>

<tr>
<td><b>Mode Reports</b></td>
<td><ul>1.<a href="https://data.shopify.com/reports/language-care-agent-performance" target="_blank">Language Care - Agent Performance</a></ul><ul>2.<a href="https://data.shopify.com/reports/agent-performance" target="_blank">Guru Performance</a></ul><ul>3.<a href="https://data.shopify.com/reports/language-care-overview" target="_blank">Language Care Overview</a></ul><ul>4.<a href="https://data.shopify.com/reports/support-country-overview/runs/49dd41971b3c" target="_blank">Support Country Overview</a></ul><ul>5.<a href="https://app.mode.com/shopify/reports/27ba35bcd506" target="_blank">About tags by language queue | Mode</a></ul><ul>6.<a href="https://data.shopify.com/reports/merchant-frustrations-by-country-and-component" target="_blank">Merchant Frustrations by country and component</a></ul><ul>7.<a href="https://artifact.shopify.io/" target="_blank">Artifact - reports directory</a></ul><ul>If any of the above reports do not work for you, it might be because they have changed location. Use <a href="https://artifact.shopify.io/" target="_blank">Artifact</a> to search for the report with the title mentioned here.</ul></td>
<td><ul>1. This report helps you see average performance and smiley per teams/groups</ul><ul>2. This report helps you see details about smileys and tickets feedback.</ul><ul>3. Overview of LC tickets per group, SLO%, Smiley %, Interactions count & First Response timing.</ul><ul>4. The data below looks at Ticket and Interaction tables and Support's Shop information to examine information relating to interactions requested by Merchants on a Location Specific Basis and responded to by All Teams. </ul><ul>5. Review top 15 About tags and topic count by language group. </ul><ul>6. Select a country code and/or component to see Merchant Frustrations and the number of tickets escalated.</ul><ul>7. Artifact is a dataset discovery tool built to centralize and surface contextual metadata for all of Shopifyâ€™s datasets, and the relationships between them.</ul></td>
</tr>
</tbody>
</table>
